api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/json']
    formats:
        html: ['text/html']
        jsonld: ['application/ld+json']
        jsonapi: ['application/vnd.api+json']
        json: ['application/json']
        multipart: ['multipart/form-data']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    defaults:
        pagination_client_enabled: true
    collection:
        pagination:
            enabled_parameter_name: pagination
