nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: [ "Content-Type","Accept","X-Requested-With","remember-me", 'Authorization']
        expose_headers: ['Link']
        max_age: 1296000
        hosts: []
        forced_allow_origin_value: ~
