vich_uploader:
  db_driver: orm
  metadata:
    type: annotation
  mappings:
    media_object:
      uri_prefix: '%env(BACKEND_URL)%media'
      upload_destination: '%kernel.project_dir%/public/media'
      namer: Vich\UploaderBundle\Naming\UniqidNamer